# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-22 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fastest_laps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_prix', models.CharField(max_length=15)),
                ('driver', models.CharField(max_length=25)),
                ('car_model', models.CharField(max_length=50)),
                ('time_taken', models.TimeField(blank=True)),
            ],
        ),
    ]
